### ISSUE TITLE
Cannot create sample points from a convexhull.

### ISSUE THREAD

**Issue by gluonhiggs** [hongkai-dai/large_inscribed_ellipsoid#1]
Hi! I tried to substitute the following data into your code:
`[[2262, 0], [2263, 0], [2264, 0], [2265, 0], [2266, 0], [2267, 0], [2268, 0], [2269, 0], [2270, 0], [2271, 0], [2272, 0], [2273, 0], [2274, 0], [2275, 0], [2276, 0], [2277, 0], [2278, 0], [2279, 0], [2280, 0], [2281, 0], [2282, 0], [2283, 0], [2284, 0], [2285, 0], [2286, 0], [2287, 0], [2288, 0], [2289, 0], [2290, 0], [2291, 0], [2292, 0], [2293, 0], [2294, 0], [2295, 0], [2296, 0], [2297, 0], [2298, 0], [2299, 0], [2300, 0], [2301, 0], [2302, 0], [2303, 0], [2304, 0], [2305, 0], [2306, 0], [2307, 0], [2308, 0], [2309, 0], [2310, 0], [2311, 0], [2312, 0], [2313, 0], [2314, 0], [2315, 0], [2316, 0], [2317, 0], [2318, 0], [2319, 0], [2320, 0], [2321, 0], [2322, 0], [2323, 0], [2324, 0], [2325, 0], [2326, 0], [2327, 0], [2328, 0], [2329, 0], [2330, 0], [2331, 0], [2332, 0], [2333, 0], [2334, 0], [2335, 0], [2336, 0], [2337, 0], [2338, 0], [2339, 0], [2340, 0], [2341, 0], [2342, 0], [2343, 0], [2344, 0], [2345, 0], [2346, 0], [2347, 0], [2348, 0], [2349, 0], [2350, 0], [2351, 0], [2352, 0], [2353, 0], [2354, 0], [2262, 1], [2354, 1], [2262, 2], [2354, 2], [2262, 3], [2354, 3], [2263, 4], [2354, 4], [2263, 5], [2354, 5], [2263, 6], [2354, 6], [2263, 7], [2354, 7], [2264, 8], [2354, 8], [2264, 9], [2354, 9], [2264, 10], [2354, 10], [2265, 11], [2354, 11], [2266, 12], [2354, 12], [2266, 13], [2354, 13], [2267, 14], [2354, 14], [2268, 15], [2354, 15], [2268, 16], [2354, 16], [2269, 17], [2354, 17], [2270, 18], [2354, 18], [2270, 19], [2354, 19], [2271, 20], [2354, 20], [2271, 21], [2354, 21], [2271, 22], [2354, 22], [2272, 23], [2354, 23], [2273, 24], [2354, 24], [2274, 25], [2354, 25], [2274, 26], [2354, 26], [2274, 27], [2354, 27], [2273, 28], [2354, 28], [2273, 29], [2354, 29], [2274, 30], [2354, 30], [2273, 31], [2354, 31], [2274, 32], [2354, 32], [2274, 33], [2354, 33], [2274, 34], [2354, 34], [2275, 35], [2354, 35], [2276, 36], [2354, 36], [2277, 37], [2278, 37], [2354, 37], [2279, 38], [2354, 38], [2280, 39], [2354, 39], [2281, 40], [2354, 40], [2280, 41], [2354, 41], [2280, 42], [2354, 42], [2280, 43], [2354, 43], [2281, 44], [2354, 44], [2281, 45], [2354, 45], [2281, 46], [2354, 46], [2281, 47], [2354, 47], [2281, 48], [2354, 48], [2282, 49], [2354, 49], [2282, 50], [2354, 50], [2282, 51], [2354, 51], [2282, 52], [2354, 52], [2283, 53], [2354, 53], [2283, 54], [2354, 54], [2283, 55], [2354, 55], [2284, 56], [2354, 56], [2284, 57], [2354, 57], [2284, 58], [2354, 58], [2284, 59], [2354, 59], [2285, 60], [2354, 60], [2285, 61], [2354, 61], [2285, 62], [2354, 62], [2285, 63], [2354, 63], [2285, 64], [2354, 64], [2285, 65], [2354, 65], [2286, 66], [2354, 66], [2286, 67], [2354, 67], [2286, 68], [2354, 68], [2286, 69], [2354, 69], [2287, 70], [2354, 70], [2287, 71], [2354, 71], [2287, 72], [2354, 72], [2287, 73], [2354, 73], [2287, 74], [2354, 74], [2287, 75], [2354, 75], [2287, 76], [2354, 76], [2288, 77], [2354, 77], [2288, 78], [2354, 78], [2288, 79], [2354, 79], [2288, 80], [2354, 80], [2289, 81], [2354, 81], [2289, 82], [2354, 82], [2289, 83], [2354, 83], [2289, 84], [2354, 84], [2289, 85], [2338, 85], [2347, 85], [2348, 85], [2349, 85], [2350, 85], [2351, 85], [2352, 85], [2353, 85], [2354, 85], [2289, 86], [2331, 86], [2333, 86], [2334, 86], [2335, 86], [2336, 86], [2337, 86], [2339, 86], [2340, 86], [2341, 86], [2346, 86], [2289, 87], [2329, 87], [2330, 87], [2332, 87], [2342, 87], [2343, 87], [2344, 87], [2345, 87], [2290, 88], [2328, 88], [2290, 89], [2327, 89], [2290, 90], [2322, 90], [2323, 90], [2324, 90], [2325, 90], [2326, 90], [2290, 91], [2321, 91], [2291, 92], [2321, 92], [2291, 93], [2321, 93], [2292, 94], [2320, 94], [2321, 94], [2292, 95], [2319, 95], [2292, 96], [2293, 96], [2318, 96], [2294, 97], [2295, 97], [2318, 97], [2296, 98], [2297, 98], [2318, 98], [2298, 99], [2299, 99], [2317, 99], [2300, 100], [2301, 100], [2317, 100], [2302, 101], [2303, 101], [2316, 101], [2317, 101], [2304, 102], [2305, 102], [2313, 102], [2314, 102], [2315, 102], [2306, 103], [2307, 103], [2312, 103], [2308, 104], [2309, 104], [2310, 104], [2311, 104]]`
That is a set of given points. We can convert the list into a numpy array then run your code. Eventually, the run returned this:
`C:\Users\hoang\anaconda3\lib\site-packages\cvxpy\problems\problem.py:1294: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
  warnings.warn(
.\2088_1st_stackoverflow_alg.py:37: RuntimeWarning: invalid value encountered in true_divide
  sample = np.random.choice(len(vols), size=n, p=vols / vols.sum())
Traceback (most recent call last):
  File ".\2088_1st_stackoverflow_alg.py", line 227, in <module>
    P, q, r = find_large_ellipsoid(pts, max_iterations)
  File ".\2088_1st_stackoverflow_alg.py", line 209, in find_large_ellipsoid
    sample_pts = uniform_sample_from_convex_hull(deln, dim, 20)
  File ".\2088_1st_stackoverflow_alg.py", line 37, in uniform_sample_from_convex_hull
    sample = np.random.choice(len(vols), size=n, p=vols / vols.sum())
  File "mtrand.pyx", line 929, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN`
So in this particular case, the initial vols is an array of 0, and the uniform_sample_from_convex_hull is not working as we wish.

**Comment by hongkai-dai** [comment]
Thanks a lot for reporting the problem. There is indeed a bug in my code. I fixed the bug in the github repo already. Could you try it now?

I ran the code with your example, and here is the ellipsoid it finds
![Figure_1](https://user-images.githubusercontent.com/6314000/141692768-72d153e3-620a-47f4-9c79-3addd554e9bd.png)

Notice that I have to use Mosek instead of the default SCS solver.

If it works on your side, could you close this issue? Thanks a lot!

**Comment by gluonhiggs** [comment]
If I only use your code, the error would be:
`C:\Users\hoang\anaconda3\lib\site-packages\cvxpy\problems\problem.py:1294: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
  warnings.warn(
Traceback (most recent call last):
  File ".\2088_1st_stackoverflow_alg.py", line 251, in <module>
    P, q, r = find_large_ellipsoid(pts, max_iterations)
  File ".\2088_1st_stackoverflow_alg.py", line 235, in find_large_ellipsoid
    is_in_ellipsoid = np.sum(sample_pts.T*(P_best @ sample_pts.T), axis=0)\
UnboundLocalError: local variable 'P_best' referenced before assignment`
This error happens quite very often, which implies the initial P_best cannot be generated.
So to avoid this one, do you mean you have to use mosek to find the initial values of P, q, r? I suspect we cannot get a solution if we purely use the repo code.
And one more thing, I don't understand the part `prob = cp.Problem(cp.Minimize(0), constraints)`. How can this works when we Minimize(0)? Isn't it to Minimize a function which is 0?

**Comment by hongkai-dai** [comment]
Every `P, q, r` are found through solving SDP. I would recommend to install Mosek for solving this SDP. As the error message says, that with the solver on your machine (probably SCS), the solution is inaccurate.

`prob = cp.Problem(cp.Minimize(0), constraints)` means we solve a feasibility problem, and don't care about the cost function. (The cost is always 0). As explained in the stackoverflow answer, this algorithm solves an SDP to find an ellipsoid that covers the "inner_pts`, and covers no `outer_pts`. This SDP doesn't have a cost function.

**Comment by hongkai-dai** [comment]
BTW, once you install mosek (I did it through `pip3 install mosek`), then cvxpy will automatically prefers using Mosek to solve this problem. You don't need to change the code.

**Comment by gluonhiggs** [comment]
I think I need to reconfigure my local environment to test the code. There are a couple of cases that we cannot just run the code straightforwardly, for examples: virtualenv, using anaconda instead of python, cloud platform like colab... In such cases, either Error related to Mosek license pops out (virtualenv, anaconda) or the environment doesn't prioritize using mosek as a solver (colab). However, as you mentioned, the code is fine with the way you set up mosek, I believe it, so far. Thank you for the answers!

**Comment by gluonhiggs** [comment]
License error ref: [here]( https://docs.mosek.com/latest/licensing/client-setup.html)

**Comment by hongkai-dai** [comment]
In case it would help
1. On my local machine, I also have virtualenv. I activate the virtual env, and then download Mosek on my machine, run `pip3 install mosek`. Now I can run mosek python interface within this virtual env.
2. Mosek also says that one can run their solver on colab, as mentioned in this page https://solve.mosek.com/web/index.html
3. You can change this line https://github.com/hongkai-dai/large_inscribed_ellipsoid/blob/41ab1a488f60945c6dcdb7d1d612c644e64c73bc/max_inner_ellipsoid.py#L119 to
   ```
   prob.solver(verbose=True, solve=cp.MOSEK)
   ```
   which can print info.

**Comment by gluonhiggs** [comment]
<2> Not quite working for this particular case.
<1, 3> Yeah. Thanks. However, for various sets of points, it's hard to estimate which value of `max_iterations` should be used. Even for the mentioned set, I had to try `max_iterations`  as 10, 100, 200, 500, I still couldn't find the best ellipse. If `max_iterations` is 1000, the `find_large_ellipsoid` only returns 3 values, not 5 as intended. I think we can use L2 norm of difference between two consecutive solutions `(P, q, r)` and `(P', q', r')` as a stopping condition. What do you think?

**Comment by hongkai-dai** [comment]
> If max_iterations is 1000, the find_large_ellipsoid only returns 3 values, not 5 as intended.

That is a bug in the code, I just fixed the code.

>  think we can use L2 norm of difference between two consecutive solutions (P, q, r) and (P', q', r') as a stopping condition. What do you think?

That is a good idea. We can use the increase in the ellipse volume as the stopping criteria, I can add it in the next commit

**Comment by hongkai-dai** [comment]
I added the volume increase as the stopping criteria.

**Comment by gluonhiggs** [comment]
Is it necessary to combine both` max_iterations` and `volume_tol` for stopping condition? Because the purpose is to find the best ellipse, we only need to compare two consecutive solutions such as `(P, q, r)` and `(P',q',r')`. If the difference between them is negligible, either one of them is good to be accepted. On the other hand, what if for any large number of points, we cannot estimate `max_iterations`. Suppose we guess we only need 1000, but the `max_iterations` needed is 3000, to get close to the best ellipse. In such a case, we have to change the value of it, and run again, not to mention that a run takes really long time. Do you have any comment?

**Comment by hongkai-dai** [comment]
Currently the logic in the code is that when either of the condition is satisfied
1. Reach max_iterations
2. The change of volume is smaller than volume_tol

The process will terminate.

So you could set `max_iterations` to be very high (like 10000), and use `volume_tol` to terminate.

I will later add another commit, such that you can take the result from one `find_large_ellipsoid`, and then continue to solve the problem using that result as the initial guess of the second `find_large_ellipsoid`. So that you can choose a small max_iterations, and check whether you like the result when the algorithm terminates with small max_iterations. If you want to further improve that result, you can run the second `find_large_ellipsoid`.

**Comment by hongkai-dai** [comment]
@resduo I added the new class FindLargeEllipsoid. Using this class you can improve the previous search result. So you can first use a small `max_iterations` to find a solution. If you are not satisfied with that solution, you can improve upon it using [search_from](https://github.com/hongkai-dai/large_inscribed_ellipsoid/blob/8e82e662041e651b29267533ab2ee54e3087473d/max_inner_ellipsoid.py#L261) function. You can also find its demo in `demo2.py`, which comes directly from your example.

**Comment by gluonhiggs** [comment]
Wow. I have just tested your code. The run is really fast! I didn't expect that, but I may need a little time for understanding the improvement! Thank you!

**Comment by gluonhiggs** [comment]
I have run the code several times. I realize that the results are not consistent, the final volumes are different, the shape of the ellipses are different. I think the root cause of this is because the code generates inside points randomly. These points "orient" the direction of their corresponding ellipse and the solution. I think we can find the principal components of the given points and generate inside points based on the directions of those axes.
